blank_issues_enabled: false
contact_links:
  - name: No GitHub account? Don't know how to use GitHub?
    url: https://ybw0014.net/go/sf-qgroup
    about: Click the button on the right to join the QQ group and give feedback
